// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(PadelBookingContext))]
    partial class PadelBookingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.DataModel.ClubDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Club");
                });

            modelBuilder.Entity("Infrastructure.DataModel.ClubDataModel", b =>
                {
                    b.OwnsOne("Domain.Models.TimePeriod", "TimePeriod", b1 =>
                        {
                            b1.Property<Guid>("ClubDataModelId")
                                .HasColumnType("uuid");

                            b1.Property<TimeOnly>("End")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly>("Start")
                                .HasColumnType("time without time zone");

                            b1.HasKey("ClubDataModelId");

                            b1.ToTable("Club");

                            b1.WithOwner()
                                .HasForeignKey("ClubDataModelId");
                        });

                    b.Navigation("TimePeriod")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
